import fs from 'node:fs';
import {build} from 'esbuild';
const root=new URL('.',import.meta.url);process.chdir(root.pathname);
const read=p=>fs.readFileSync(p,'utf8');
fs.mkdirSync('dist/server',{recursive:true});
const tokens=JSON.parse(read('theme-tokens.json'));
const tokenCss=['light','dark'].map(mode=>`html[data-theme=${mode}]{${tokens.map(t=>'--'+t.name.replace('color/','').replaceAll('/','-')+':'+t[mode]).join(';')}}`).join('\n');
const mono=s=>s.replace(/(fill|stroke)="(?:#[0-9a-fA-F]{3,8}|black|white)"/gi,'$1="currentColor"');
const icons=Object.fromEntries(Object.entries(JSON.parse(read('assets/icon_exports.json'))).map(([k,v])=>[k,mono(v)]));
const brand=JSON.parse(read('assets/brand_exports.json')),newIcons=JSON.parse(read('assets/demo_new_icons.json'));
const symbol=mono(brand.brand).replace('<svg ','<svg class="brand-symbol" '),word=mono(brand.wordmark).replace('<svg ','<svg class="brand-word" ');
const logo=symbol+'<div class="brand-text">'+word+'<small>EARLY ACCESS</small></div>';
const fonts=[0,1,2,3].map(n=>`@font-face{font-family:'${n===0?'DM Serif Display':'Inter'}';font-style:normal;font-weight:${n===0?400:n===1?400:n===2?500:600};src:url(data:font/ttf;base64,${fs.readFileSync('assets/fonts/font'+n+'.ttf').toString('base64')}) format('truetype');font-display:swap}`).join('\n');
let js=read('src/app.js').replace('ICON_DATA',JSON.stringify(icons)).replace("'BRAND_SYMBOL<span>akilii</span>'",JSON.stringify(symbol+'<span>akilii</span>'));
let html=read('src/app.template.html').replaceAll('BRAND',()=>logo).replaceAll('TOGGLE',()=>mono(newIcons.toggle)).replace('>MIC</button>',()=>'>'+mono(newIcons.mic)+'</button>').replace('TOKEN_CSS',()=>tokenCss).replace('APP_CSS',()=>read('src/app.css')).replace('APP_JS',()=>js.replaceAll('</script','<\\/script')).replace('FONT_CSS',()=>fonts);
fs.writeFileSync('src/app.html',html);
fs.copyFileSync('assets/storyboard.html','src/storyboard.html');
await build({entryPoints:['src/document-tools.js'],bundle:true,format:'esm',target:'es2022',outfile:'src/document-tools.bundle.js',minify:true,legalComments:'none'});
fs.copyFileSync('node_modules/pdfjs-dist/build/pdf.worker.min.mjs','src/pdf.worker.mjs');
await build({entryPoints:['src/server.js'],bundle:true,format:'esm',platform:'browser',target:'es2022',outfile:'dist/server/index.js',loader:{'.html':'text','.bundle.js':'text','.mjs':'text'},minify:false});
fs.rmSync('dist/index.html',{force:true});
console.log('Application and document reader built.');
