import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {JSDOM} from 'jsdom';
import {build} from 'esbuild';
const source=await readFile(new URL('../src/conversation-actions.js',import.meta.url),'utf8');
function harness(){const dom=new JSDOM('<dialog id="dialog"><div id="dialog-content"></div></dialog>',{url:'https://app.test',runScripts:'outside-only'});const w=dom.window;w.$=id=>w.document.getElementById(id);w.esc=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');w.dialog=(_title,html)=>w.$('dialog-content').innerHTML=html;w.voiceSession=null;w.eval(source);return {dom,w};}
test('typed workspace changes do not save until explicit review confirmation',async()=>{const {dom,w}=harness();let saved=null;w.akiliiConversation.action({title:'Review',fields:[{key:'objective',label:'Objective',question:'What matters?'}],initial:{objective:'Old'},save:async v=>saved=v});w.$('conversation-answer').value='New';w.$('conversation-next').click();assert.equal(saved,null);assert.match(w.$('dialog-content').textContent,/Nothing has been saved/);await w.$('conversation-confirm').onclick();assert.equal(saved.objective,'New');dom.window.close();});
test('speech shares the review boundary, and spoken answers replace the initial value',async()=>{const {dom,w}=harness();let recognizer,saves=0;w.SpeechRecognition=class{constructor(){recognizer=this;}start(){}abort(){}};w.SpeechSynthesisUtterance=class{constructor(text){this.text=text;}};w.speechSynthesis={cancel(){},speak(u){u.onend();}};w.akiliiConversation.action({title:'Voice',fields:[{key:'objective',label:'Objective',question:'What matters?'}],initial:{objective:'Old'},save:async v=>{assert.equal(v.objective,'New objective');saves++;}});w.$('conversation-speech').click();const say=text=>recognizer.onresult({results:[Object.assign([{transcript:text}],{isFinal:true})]});say('New objective');assert.equal(w.$('conversation-answer').value,'New objective');say('next');assert.equal(saves,0);say('confirm these changes');await new Promise(resolve=>setImmediate(resolve));assert.equal(saves,1);dom.window.close();});
test('normal launch installs the floating composer without a Phase 8 query flag',async()=>{const html=await readFile(new URL('../src/app.template.html',import.meta.url),'utf8');const dom=new JSDOM(html.replace(/<style>[\s\S]*?<\/style>/g,''),{url:'https://app.test/',runScripts:'outside-only'});const w=dom.window;w.ResizeObserver=class{observe(){}};const bundle=await build({entryPoints:[new URL('../src/support/index.js',import.meta.url).pathname],bundle:true,write:false,format:'iife'});w.eval(bundle.outputFiles[0].text);w.akiliiSupport.install({composerContext:()=>[],useContext:()=>false});assert.equal(w.akiliiSupport.flags.enabled,false);assert.ok(w.document.querySelector('.support-floating #chat-form'));assert.ok(w.document.querySelector('#chat-form > #mic'));assert.equal(w.document.querySelector('.support-composer-popover #mic'),null);assert.equal(w.document.querySelectorAll('#mic').length,1);dom.window.close();});
