import {test} from 'node:test';import assert from 'node:assert/strict';
import {parseResponse,partialMessage,responseFormat} from '../backend/response-objects.js';
import {draftMime,seal,unseal,emailRoute} from '../backend/email.js';
import {validateProject} from '../backend/workspace.js';
test('structured response validates known objects and safely decodes fragmented strings',()=>{const response={message:'A “small” step\nfor you 🟢',objects:[{type:'checklist',title:'Begin',summary:'Keep it small',items:[{label:'Open the draft',detail:'No editing yet'}],draft:''}]};const raw=JSON.stringify(response);assert.deepEqual(parseResponse(raw),response);let last='';for(let i=1;i<=raw.length;i++){const next=partialMessage(raw.slice(0,i));assert(response.message.startsWith(next));assert(next.startsWith(last));last=next;}assert.equal(last,response.message);assert.throws(()=>parseResponse(JSON.stringify({...response,objects:[{...response.objects[0],type:'arbitrary_html'}]})));assert.equal(responseFormat.strict,true);});
test('email MIME rejects header injection and preserves unicode',()=>{assert.throws(()=>draftMime({to:'a@example.com\r\nBcc: victim@example.com',subject:'Hi',body:'Test'}));assert.throws(()=>draftMime({to:'a@example.com',subject:'Hi\r\nBcc: x',body:'Test'}));const raw=draftMime({to:'reviewer@example.test',subject:'A thoughtful next step — akilii',body:'Hello 🟢'});const mime=Buffer.from(raw,'base64url').toString();assert.match(mime,/To: reviewer@example.test\r\nSubject: =\?UTF-8\?B\?/);assert(!mime.includes('Bcc:'));});
test('email token encryption is authenticated and not stored in plaintext',async()=>{const key=Buffer.from(crypto.getRandomValues(new Uint8Array(32))).toString('base64');const ciphertext=await seal('fictional-secret',key);assert(!ciphertext.includes('fictional-secret'));assert.equal(await unseal(ciphertext,key),'fictional-secret');const other=Buffer.from(crypto.getRandomValues(new Uint8Array(32))).toString('base64');await assert.rejects(()=>unseal(ciphertext,other));});
test('email connector rejects the wrong Google identity before saving a token',async()=>{let wrote=false;const sql=async()=>{wrote=true;return[];};await assert.rejects(()=>emailRoute('/api/email/connect','POST',{access_token:'fictional'},sql,{id:'a',email:'a@example.test'},'key',async()=>new Response(JSON.stringify({email:'b@example.test',email_verified:true}),{headers:{'Content-Type':'application/json'}})),e=>e.status===403);assert.equal(wrote,false);});
test('project creation bounds tasks and never accepts model completion flags',()=>{const p=validateProject({title:'Workshop',tasks:[{title:'Start',done:true}]});assert.equal(p.tasks[0].done,false);assert.equal(validateProject({title:'Project',tasks:Array.from({length:40},()=>({title:'Step'}))}).tasks.length,30);assert.throws(()=>validateProject({title:' '}));});
