async function renderSignIn(){
 const auth=window.akiliiAuth,box=$('entry-action');
 box.innerHTML='<p role="status">Checking sign-in options…</p>';
 let options;try{options=await auth.options();}catch{box.innerHTML='<p>Sign-in options could not be loaded. Check your connection.</p><button id="retry-auth">Try again</button>';if(auth.local)box.innerHTML+='<button id="local-signin">Continue on this device</button>';$('retry-auth').onclick=renderSignIn;if($('local-signin'))$('local-signin').onclick=safely(auth.local);return;}
 box.innerHTML='<button class="primary" id="email-signin" '+(!options.email?'disabled':'')+'>Continue with email</button>'+(!options.email?'<p><small>Email codes are awaiting email-service setup.</small></p>':'')+'<div class="auth-providers">'+[['google','Google'],['azure','Microsoft']].map(([id,name])=>'<button class="sso-icon" data-auth-provider="'+id+'" aria-label="Continue with '+name+'" title="'+name+(options[id]?'':' · awaiting configuration')+'" '+(!options[id]?'disabled':'')+'><span class="sr-only">Continue with '+name+'</span></button>').join('')+'</div><p><small>Private beta · use your invited email address. Signing in does not connect your inbox.</small></p>'+(auth.local?'<button id="local-signin">Continue on this device</button><p><small>No online account needed. Local AI requires Ollama and an installed model.</small></p>':'');
 $('email-signin').onclick=()=>emailSignIn();box.querySelectorAll('[data-auth-provider]').forEach(b=>b.onclick=safely(()=>auth.signIn(b.dataset.authProvider)));if(auth.local)$('local-signin').onclick=safely(auth.local);
}
function emailSignIn(){
 dialog('Continue with email','<form id="email-auth-form"><label>Email address<input id="auth-email" type="email" autocomplete="email" maxlength="254" required></label><button class="primary" type="submit">Send sign-in code</button><p class="error" role="alert"></p></form>');
 bindForm('email-auth-form',async()=>{const email=$('auth-email').value.trim();await window.akiliiAuth.sendCode(email);dialog('Check your email','<p>Enter the sign-in code sent to '+esc(email)+'. Check spam too. Delivery can take a few minutes.</p><form id="code-auth-form"><label>Sign-in code<input id="auth-code" inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{6,10}" maxlength="10" required></label><button class="primary" type="submit">Continue</button><p class="error" role="alert"></p></form><button id="auth-change-email">Use another email</button><p><small>If a code expires, request a new one. Wait at least a minute between requests.</small></p>');$('auth-change-email').onclick=emailSignIn;bindForm('code-auth-form',async()=>{await window.akiliiAuth.verifyCode(email,$('auth-code').value.trim());$('dialog').close();await boot();});});
}
