async function renderSignIn(){
 const auth=window.akiliiAuth,box=$('entry-action');
 box.innerHTML='<p role="status">Checking sign-in options…</p>';
 let options;try{options=await auth.options();}catch{box.innerHTML='<p>Sign-in options could not be loaded. Check your connection.</p><button id="retry-auth">Try again</button>';if(auth.local)box.innerHTML+='<button id="local-signin">Continue on this device</button>';$('retry-auth').onclick=renderSignIn;if($('local-signin'))$('local-signin').onclick=safely(auth.local);return;}
 box.innerHTML='<button class="primary" id="email-signin" '+(!options.email?'disabled':'')+'>Continue with email</button>'+(!options.email?'<p><small>Email codes are awaiting email-service setup.</small></p>':'')+'<div class="auth-providers">'+[['google','Google'],['azure','Microsoft']].map(([id,name])=>'<button class="sso-icon" data-auth-provider="'+id+'" aria-label="Continue with '+name+'" title="'+name+(options[id]?'':' · awaiting configuration')+'" '+(!options[id]?'disabled':'')+'><span class="sr-only">Continue with '+name+'</span></button>').join('')+'</div><p><small>Early access · 30 places, then a waiting list. Signing in does not connect your inbox.</small></p>'+(auth.local?'<button id="local-signin">Continue on this device</button><p><small>No online account needed. Local AI requires Ollama and an installed model.</small></p>':'');
 $('email-signin').onclick=()=>emailSignIn();box.querySelectorAll('[data-auth-provider]').forEach(b=>b.onclick=safely(()=>auth.signIn(b.dataset.authProvider)));if(auth.local)$('local-signin').onclick=safely(auth.local);
}
function emailSignIn(){
 dialog('Continue with email','<form id="email-auth-form"><label>Email address<input id="auth-email" type="email" autocomplete="email" maxlength="254" required></label><button class="primary" type="submit">Send sign-in code</button><p class="error" role="alert"></p></form>');
 bindForm('email-auth-form',async()=>{const email=$('auth-email').value.trim();await window.akiliiAuth.sendCode(email);dialog('Check your email','<p>Enter the sign-in code sent to '+esc(email)+'. Check spam too. Delivery can take a few minutes.</p><form id="code-auth-form"><label>Sign-in code<input id="auth-code" inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{6,10}" maxlength="10" required></label><button class="primary" type="submit">Continue</button><p class="error" role="alert"></p></form><button id="auth-change-email">Use another email</button><p><small>If a code expires, request a new one. Wait at least a minute between requests.</small></p>');$('auth-change-email').onclick=emailSignIn;bindForm('code-auth-form',async()=>{await window.akiliiAuth.verifyCode(email,$('auth-code').value.trim());$('dialog').close();await boot();});});
}

async function renderAccessGate(){
 let access;try{access=await api('access');}catch{return false;}
 if(access.status==='admitted')return false;
 const box=$('entry-action');
 if(access.status==='blocked'){box.innerHTML='<p>Access to this preview is paused. Please contact the team.</p>';}
 else if(access.status==='waiting'){box.innerHTML='<h3>You’re on the waiting list.</h3><p>We’ll contact you when a place is available. You can return here to check.</p><button id="leave-waiting">Leave waiting list</button>'; $('leave-waiting').onclick=safely(async()=>{await api('access','DELETE');await renderAccessGate();});}
 else {const full=access.status==='full';box.innerHTML='<h3>'+(full?'The first cohort is full.':'Join the first 30.')+'</h3><p>'+(full?'Join the waiting list for the next available place.':'Create your early-access space and help shape akilii.')+'</p><label class="access-notice"><input id="access-consent" type="checkbox"> Store my verified email for '+(full?'waiting-list updates':'early access')+'. Basic account activity counts help improve the preview and report aggregate traction. Conversation content and NPR details are excluded from these metrics.</label><button class="primary" id="join-access" disabled>'+(full?'Join waiting list':'Join early access')+'</button>'; $('access-consent').onchange=()=>{$('join-access').disabled=!$('access-consent').checked;};$('join-access').onclick=safely(async()=>{const b=$('join-access');b.disabled=true;try{const result=await api('access','POST',{notice:access.notice});if(result.status==='admitted')await boot();else await renderAccessGate();}finally{if(b.isConnected)b.disabled=false;}});}
 const out=document.createElement('button');out.className='text-link';out.textContent='Use another account';out.onclick=safely(window.akiliiAuth.signOut);box.append(out);return true;
}
document.querySelectorAll('.download-options a').forEach((a,i)=>a.addEventListener('click',()=>{api('traction-event','POST',{event:['download_mac_intel','download_mac_arm','download_windows'][i]}).catch(()=>{});}));
async function showTraction(){try{const report=await api('traction');dialog('Early-access traction','<p>Owner-only aggregate reporting</p><dl>'+Object.entries(report).filter(([k,v])=>typeof v==='number').map(([k,v])=>'<dt>'+esc(k.replaceAll('_',' '))+'</dt><dd>'+esc(v)+'</dd>').join('')+'</dl><p>'+report.notes.map(esc).join('<br>')+'</p><button id="export-traction">Export metrics JSON</button>');$('export-traction').onclick=()=>download(JSON.stringify(report,null,2),'akilii-traction.json','application/json');}catch(e){toast(e.message);}}

const baseSettingsForAccess=settingsView;
settingsView=function(){baseSettingsForAccess();if(window.akiliiAuth?.mode==='local')return;api('traction').then(()=>{if(S.view!=='settings')return;const button=document.createElement('button');button.textContent='Early-access traction';button.onclick=showTraction;$('content-view').append(button);}).catch(()=>{});};
