/* Living Context UI. This augments the legacy flat-memory surface without making local mode pretend to have cloud NPR parity. */
const LC={data:null,loading:null,lastLoaded:0};
const lcTypeLabel={user_assertion:'About me',communication_preference:'Communication',support_preference:'Support',observation:'Something akilii is testing',goal:'Goal',friction:'Friction',strategy:'What helps',relationship_reference:'Relationship'};
function lcValue(item){const p=item?.payload||{};for(const key of ['statement','description','strategy','title','hypothesis','value']){if(typeof p[key]==='string'&&p[key].trim())return p[key].trim();}return 'Structured context';}
function lcPayloadKey(item){const p=item?.payload||{};return ['statement','description','strategy','title','hypothesis','value'].find(key=>typeof p[key]==='string')||'statement';}
function lcFallback(){const d=S.data;if(!d?.profile)return null;return {legacy:true,items:[...(d.profile.focus?[{id:'legacy-focus',itemType:'goal',payload:{title:d.profile.focus},lifecycleState:'active',confirmationState:'user_asserted',use_allowed:true,version:1}]:[]),...(d.profile.style?[{id:'legacy-style',itemType:'user_assertion',payload:{statement:d.profile.style},lifecycleState:'active',confirmationState:'user_asserted',use_allowed:true,version:1}]:[]),...(d.memories||[]).map(m=>({id:m.id,itemType:'user_assertion',payload:{statement:m.content},lifecycleState:'active',confirmationState:'user_asserted',use_allowed:true,version:1}))],proposals:[],controls:{default_use_context:true,sensitive_context_allowed:false,proactive_discovery:false}};}
async function lcLoad(force=false){
 if(!force&&LC.data&&Date.now()-LC.lastLoaded<15000)return LC.data;
 if(LC.loading)return LC.loading;
 LC.loading=(async()=>{try{const data=await api('context');try{const projected=await api('context/project','POST',{purpose:'support',activity:'context_review',objective:'progressively understand how to support me',message:'',execution:false});data.discovery=projected.discovery;data.supportProfile=projected.supportProfile;}catch{}LC.data=data;LC.lastLoaded=Date.now();return data;}catch(error){if([404,405,501].includes(error.status)){LC.data=lcFallback();LC.lastLoaded=Date.now();return LC.data;}throw error;}finally{LC.loading=null;}})();
 return LC.loading;
}
function lcCard(label,title,copy,extra=''){return `<div class="context-card"><span class="eyebrow">${esc(label)}</span><h4>${esc(title)}</h4><p>${esc(copy)}</p>${extra}</div>`;}
function lcScope(item){const scopes=item.purpose_scopes||item.controls?.purposeScopes||[];return scopes.length?scopes.join(', '):'eligible uses';}
function lcRenderPanel(data){
 if(!data)return;
 const on=$('use-context').checked;
 const active=(data.items||[]).filter(i=>i.lifecycleState==='active'&&i.use_allowed!==false).slice(0,4);
 const pending=(data.proposals||[]).filter(p=>p.status==='pending');
 const profile=data.supportProfile;
 let html=lcCard(on?'AVAILABLE FOR YOUR NEXT MESSAGE':'PAUSED FOR YOUR NEXT MESSAGE',on?'Context can shape the support, not define you.':'A fresh perspective.',on?'Only eligible context you have allowed can be projected into this interaction.':'Saved context remains yours, but it will not be included in the next message.');
 if(profile)html+=lcCard('CURRENT SUPPORT SHAPE','How akilii is adapting',`${profile.representation.replaceAll('_',' ')} · ${profile.responseLength} responses · ${profile.decomposition} decomposition. This is an interaction setting, not a label about you.`);
 if(active.length)html+=active.map(item=>lcCard(lcTypeLabel[item.itemType]||'CONTEXT',lcValue(item),`Source: ${item.confirmationState==='user_asserted'?'you':item.confirmationState}. Use: ${lcScope(item)}.`)).join('');
 else html+=lcCard('LIVING CONTEXT','Still getting to know you','Nothing here is required before akilii can help. Useful context can build gradually through real work and conversation.');
 if(pending.length)html+=lcCard('REVIEW NEEDED',`${pending.length} proposed ${pending.length===1?'learning':'learnings'}`,'akilii will not use these as confirmed personal context until you decide.');
 if(data.discovery?.question)html+=lcCard('OPTIONAL DISCOVERY','One useful question',data.discovery.question,'<button id="lc-answer-discovery">Answer when useful →</button>');
 html+='<button id="panel-manage">Review what akilii understands →</button>';
 $('context-content').innerHTML=html;
 $('memory-count').textContent=String((data.items||[]).filter(i=>i.lifecycleState==='active').length+(data.proposals||[]).filter(p=>p.status==='pending').length);
 $('panel-manage').onclick=()=>lcManager();
 if($('lc-answer-discovery'))$('lc-answer-discovery').onclick=()=>lcDiscovery(data.discovery);
 if(typeof appendWorkspaceContext==='function')appendWorkspaceContext();
}
function context(){
 const activePanel=document.querySelector('[data-panel][aria-pressed=true]');if(activePanel&&activePanel.dataset.panel!=='context')return;
 if(!S.data?.profile)return;
 $('context-content').innerHTML=lcCard('LIVING CONTEXT','Loading what you control…','akilii is checking your current context and permissions.');
 lcLoad().then(lcRenderPanel).catch(error=>{$('context-content').innerHTML=lcCard('CONTEXT UNAVAILABLE','Your saved work is still safe',error.message||'Context could not be loaded. Continue without personal context or try again.');});
}
async function lcRefresh(){const data=await lcLoad(true);lcRenderPanel(data);return data;}
function lcManager(){
 lcLoad().then(data=>{
  if(data?.legacy){dialog('What akilii knows right now','<p>This device/build is using the earlier context model. Cloud Living Context is not available here yet; your existing profile and saved preferences remain unchanged.</p><button id="lc-close-legacy">Close</button>');$('lc-close-legacy').onclick=()=>$('dialog').close();return;}
  const items=(data.items||[]).filter(i=>!['deleted','superseded'].includes(i.lifecycleState));
  const proposals=(data.proposals||[]).filter(p=>p.status==='pending');
  const c=data.controls||{};
  const itemHtml=items.length?items.map(i=>`<article class="content-card" data-lc-item="${esc(i.id)}"><span class="eyebrow">${esc(lcTypeLabel[i.itemType]||i.itemType)} · ${esc(i.tier||'')}</span><h3>${esc(lcValue(i))}</h3><p>${i.confirmationState==='user_asserted'?'You told akilii this.':i.confirmationState==='confirmed'?'You confirmed this.':'This has not been confirmed.'} ${i.sensitivity&&i.sensitivity!=='standard'?'Sensitivity: '+esc(i.sensitivity)+'.':''}</p><p><small>${i.use_allowed===false?'Not eligible for future use.':'Eligible only within its allowed purpose and sensitivity controls.'}</small></p><div class="living-actions"><button data-lc-correct="${esc(i.id)}">Correct</button><button data-lc-toggle="${esc(i.id)}">${i.use_allowed===false?'Allow use':'Restrict use'}</button><button data-lc-delete="${esc(i.id)}">Delete</button></div></article>`).join(''):'<p>No governed context yet. You can still use akilii normally.</p>';
  const proposalsHtml=proposals.length?'<h3>Proposed learning</h3>'+proposals.map(p=>`<article class="content-card" data-lc-proposal="${esc(p.id)}"><span class="eyebrow">PROPOSED · NOT YET USED AS CONFIRMED CONTEXT</span><h3>${esc(lcValue({payload:p.proposed_item?.payload||{}}))}</h3><p>${esc(p.plain_language_reason||'Review before deciding whether this should influence later support.')}</p><div class="living-actions"><button class="primary" data-lc-confirm="${esc(p.id)}">Keep this</button><button data-lc-reject="${esc(p.id)}">Not for me</button></div></article>`).join(''):'';
  dialog('What akilii understands about you',`<p>This is a working model built with you, not an objective profile or diagnosis. Correct, restrict or delete anything that does not fit.</p><section class="content-card"><h3>Context controls</h3><label class="check"><input id="lc-default-use" type="checkbox" ${c.default_use_context!==false?'checked':''}> Allow eligible context to be available when I choose “Use my context”</label><label class="check"><input id="lc-sensitive" type="checkbox" ${c.sensitive_context_allowed===true?'checked':''}> Allow context marked sensitive to be projected when relevant</label><label class="check"><input id="lc-discovery" type="checkbox" ${c.proactive_discovery!==false?'checked':''}> Let akilii offer occasional optional discovery questions</label><button id="lc-save-controls" class="primary">Save context controls</button></section>${proposalsHtml}<h3>Your confirmed context</h3>${itemHtml}<button id="lc-add-own">Add something yourself</button>`);
  $('lc-save-controls').onclick=safely(async()=>{await api('context/controls','POST',{defaultUseContext:$('lc-default-use').checked,sensitiveContextAllowed:$('lc-sensitive').checked,proactiveDiscovery:$('lc-discovery').checked});await lcRefresh();toast('Context controls saved.');});
  document.querySelectorAll('[data-lc-confirm]').forEach(b=>b.onclick=safely(async()=>{await api('context/proposals/'+b.dataset.lcConfirm+'/confirm','POST',{});await lcRefresh();lcManager();toast('Kept. Future eligible interactions can use it.');}));
  document.querySelectorAll('[data-lc-reject]').forEach(b=>b.onclick=safely(async()=>{await api('context/proposals/'+b.dataset.lcReject+'/reject','POST',{});await lcRefresh();lcManager();toast('Rejected. It will not become confirmed context.');}));
  document.querySelectorAll('[data-lc-toggle]').forEach(b=>b.onclick=safely(async()=>{const item=items.find(i=>i.id===b.dataset.lcToggle);await api('context/'+encodeURIComponent(item.id),'POST',{version:item.version,useAllowed:item.use_allowed===false});await lcRefresh();lcManager();toast(item.use_allowed===false?'Context use allowed again.':'Context restricted.');}));
  document.querySelectorAll('[data-lc-delete]').forEach(b=>b.onclick=()=>{const item=items.find(i=>i.id===b.dataset.lcDelete);dialog('Delete this context?',`<p>${esc(lcValue(item))}</p><p>This removes it from future canonical context use. It does not rewrite old conversations or provider retention.</p><button id="lc-confirm-delete" class="primary">Delete</button><button id="lc-cancel-delete">Cancel</button>`);$('lc-cancel-delete').onclick=lcManager;$('lc-confirm-delete').onclick=safely(async()=>{await api('context/'+encodeURIComponent(item.id),'DELETE');await lcRefresh();lcManager();toast('Context deleted from future use.');});};
  document.querySelectorAll('[data-lc-correct]').forEach(b=>b.onclick=()=>lcCorrect(items.find(i=>i.id===b.dataset.lcCorrect));
  $('lc-add-own').onclick=()=>lcAddOwn();
 }).catch(error=>toast(error.message));
}
function lcCorrect(item){const key=lcPayloadKey(item),value=lcValue(item);dialog('Correct what akilii understands',`<p>Change this in your own words. The corrected version replaces the current value for future eligible use.</p><form id="lc-correct-form"><label>Corrected context<textarea id="lc-correct-value" maxlength="1500" required>${esc(value)}</textarea></label><button class="primary">Save correction</button></form>`);$('lc-correct-form').onsubmit=safely(async event=>{event.preventDefault();const next=$('lc-correct-value').value.trim();if(!next)throw new Error('Write the corrected context first.');await api('context/'+encodeURIComponent(item.id),'POST',{version:item.version,payload:{...(item.payload||{}),[key]:next}});await lcRefresh();$('dialog').close();toast('Correction saved.');});}
function lcAddOwn(){dialog('Add something you want akilii to know',`<form id="lc-add-form"><p>This is saved as something you explicitly told akilii, not something the system inferred.</p><label>What should akilii know?<textarea id="lc-add-value" maxlength="1500" required></textarea></label><label>Where may it help?<select id="lc-add-scope"><option value="support">Support conversations</option><option value="planning">Planning</option><option value="action">Work and action</option><option value="all">Support, planning and action</option></select></label><button class="primary">Keep this context</button></form>`);$('lc-add-form').onsubmit=safely(async event=>{event.preventDefault();const value=$('lc-add-value').value.trim();if(!value)throw new Error('Write something first.');const scope=$('lc-add-scope').value;await api('context/assertions','POST',{itemType:'user_assertion',tier:'semi_stable',payload:{statement:value,domain:'user_added'},sensitivity:'standard',purposeScopes:scope==='all'?['support','planning','action']: [scope],sourceRef:'user-added:'+crypto.randomUUID()});await lcRefresh();$('dialog').close();toast('Added to your governed context.');});}
function lcDiscovery(discovery){if(!discovery?.question)return;dialog('Help akilii understand you over time',`<form id="lc-discovery-form"><span class="eyebrow">OPTIONAL · ONE QUESTION</span><h3>${esc(discovery.question)}</h3><label>Your answer<textarea id="lc-discovery-answer" maxlength="1500" required></textarea></label><div class="living-actions"><button class="primary">Keep my answer</button><button id="lc-discovery-later" type="button">Not now</button></div></form>`);$('lc-discovery-later').onclick=()=>$('dialog').close();$('lc-discovery-form').onsubmit=safely(async event=>{event.preventDefault();const answer=$('lc-discovery-answer').value.trim();if(!answer)throw new Error('Write an answer first.');let payload={statement:answer,domain:'progressive_discovery'};if(discovery.type==='goal')payload={title:answer,horizon:'current',status:'active'};else if(discovery.type==='communication_preference')payload={dimension:'presentation',value:answer,context:'general'};else if(discovery.type==='friction')payload={description:answer,context:'general'};else if(discovery.type==='support_preference')payload={strategy:'user_described',description:answer,context:'general'};else if(discovery.type==='strategy')payload={description:answer,context:'general',status:'user_asserted'};await api('context/assertions','POST',{itemType:discovery.type,tier:discovery.type==='goal'?'dynamic':'semi_stable',payload,sensitivity:'standard',purposeScopes:['support','planning','action'],sourceRef:'discovery:'+discovery.type});await lcRefresh();$('dialog').close();toast('Thanks. akilii can use that only within your context controls.');});}
function memoryEditor(message){const initial=(message?.content||'').trim();dialog('Keep something useful from this conversation',`<form id="lc-remember-form"><p>Edit this into something that is genuinely about how you want akilii to support you. Saving makes it an explicit statement from you, not an inferred fact.</p><label>What should akilii remember?<textarea id="lc-remember-value" maxlength="1500" required>${esc(initial)}</textarea></label><button class="primary">Keep this context</button></form>`);$('lc-remember-form').onsubmit=safely(async event=>{event.preventDefault();const value=$('lc-remember-value').value.trim();if(!value)throw new Error('Write the context you want to keep.');try{await api('context/assertions','POST',{itemType:'user_assertion',tier:'semi_stable',payload:{statement:value,domain:'conversation'},sensitivity:'standard',purposeScopes:['support','planning'],sourceRef:message?.id?'conversation:'+message.id:'conversation:'+crypto.randomUUID()});await lcRefresh();$('dialog').close();toast('Kept in your governed context.');}catch(error){if([404,405,501].includes(error.status)){return legacyMemoryEditor(message);}throw error;}});}
function legacyMemoryEditor(message){dialog('Context is not available in this mode','<p>This device/build still uses the earlier memory model. Continue using its existing Remember control until Living Context parity is implemented here.</p><button id="lc-legacy-close">Close</button>');$('lc-legacy-close').onclick=()=>$('dialog').close();}
// Replace the legacy My akilii destination with the governed context manager where the endpoint is available.
document.querySelectorAll('[data-view="memory"]').forEach(button=>button.onclick=()=>lcManager());
