ICONS.projects='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="4" width="18" height="16" rx="3"/><path d="M8 8v8M12 8v5M16 8v7"/></svg>';
ICONS.mail='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><rect x="3" y="5" width="18" height="14" rx="3"/><path d="m4 7 8 6 8-6" stroke-linecap="round" stroke-linejoin="round"/></svg>';
/* Interactive objects are data rendered by known components; never model HTML. */
const X={settings:{role:'',objective:'',presentation:'balanced',needs:''},projects:[],projectId:null,loaded:false};
function richAnswer(content){try{const d=JSON.parse(content);if(typeof d.message==='string'&&Array.isArray(d.objects)&&d.objects.every(o=>o&&typeof o.title==='string'&&typeof o.summary==='string'&&typeof o.draft==='string'&&Array.isArray(o.items)&&o.items.every(i=>typeof i.label==='string'&&typeof i.detail==='string')))return d;}catch{}return null;}
function plainAnswer(content){const d=richAnswer(content);return d?[d.message,...d.objects.map(o=>[o.title,o.summary,...o.items.map(i=>i.label+(i.detail?' — '+i.detail:'')),o.draft].filter(Boolean).join('\n'))].filter(Boolean).join('\n\n'):content;}
function renderAnswer(target,content){
 const d=richAnswer(content);target.replaceChildren();
 const prose=document.createElement('div');prose.className='response-prose';prose.textContent=d?d.message:content;target.append(prose);if(!d)return;
 for(const o of d.objects.slice(0,3)){
  const card=document.createElement('section');card.className='response-object object-'+o.type;
  const label={checklist:'A DOABLE NEXT STEP',decision:'ROOM TO DECIDE',project:'FROM INTENTION TO ACTION',email:'WORDS YOU CAN MAKE YOURS',reflection:'A LITTLE MORE UNDERSTOOD'}[o.type]||'YOUR NEXT STEP';
  card.innerHTML=`<div class="object-heading"><span class="object-glyph" aria-hidden="true">${({checklist:'✓',decision:'↔',project:'↗',email:'✉',reflection:'◌'})[o.type]||'◌'}</span><span class="eyebrow">${label}</span></div><h3>${esc(o.title)}</h3><p>${esc(o.summary)}</p>`;
  const items=document.createElement('div');items.className='object-items';
  o.items.slice(0,10).forEach((item,index)=>{const row=document.createElement(o.type==='checklist'?'label':'div');row.className='object-item';row.innerHTML=(o.type==='checklist'?'<input type="checkbox" aria-label="'+esc(item.label)+'">':'<span class="step-number">'+String(index+1).padStart(2,'0')+'</span>')+`<div><strong>${esc(item.label)}</strong><p>${esc(item.detail)}</p></div>`;if(o.type==='checklist')row.querySelector('input').onchange=e=>{row.classList.toggle('done',e.target.checked);};items.append(row);});card.append(items);
  if(o.draft){const draft=document.createElement('p');draft.className='email-preview';draft.textContent=o.draft;card.append(draft);}
  const bar=document.createElement('div');bar.className='object-actions';
  const button=(label,fn)=>{const b=document.createElement('button');b.type='button';b.textContent=label;b.onclick=safely(fn);bar.append(b);};
  if(o.type==='email')button('Review email draft',()=>emailEditor(o.title,o.draft));
  else if(['project','checklist'].includes(o.type))button('Make this a project',()=>projectEditor(o));
  else button('Save this to Work',()=>workEditor(null,plainAnswer(JSON.stringify({message:'',objects:[o]}))));
  button(o.type==='decision'?'Explore an option':'Adapt this with me',()=>{$('message-input').value='Help me adapt “'+o.title+'” to my situation. Ask one useful question.';$('message-input').focus();});
  if(['checklist','project'].includes(o.type)&&o.items.length>1){const reveal=document.createElement('button');reveal.className='reveal-steps';reveal.textContent='Show all '+o.items.length+' steps';reveal.onclick=()=>{card.classList.toggle('show-all');reveal.textContent=card.classList.contains('show-all')?'Show one step':'Show all '+o.items.length+' steps';};card.append(reveal);}
  card.append(bar);if(o.type==='checklist'){const note=document.createElement('small');note.textContent='Checks here are temporary. Make this a project to save progress.';card.append(note);}target.append(card);
 }
}
async function loadWorkspace(){if(!window.akiliiAuth||!S.data?.profile)return;try{const d=await api('workspace');X.settings=d.settings;X.projects=d.projects;X.loaded=true;if(X.projectId&&!X.projects.some(p=>p.id===X.projectId))X.projectId=null;applyWorkspace();}catch(e){if(e.status!==404)toast(e.message);}}
function applyWorkspace(){paintAvatar();document.documentElement.dataset.presentation=X.settings.presentation;const selected=X.projects.find(p=>p.id===X.projectId);if($('project-scope')){$('project-scope').textContent=selected?'Working on: '+selected.title:'Choose project context';$('project-scope').title=selected?.objective||'Only a project you select is sent to the AI.';}context();if(S.view==='home')homeView();}
function initExperience(){
 const nav=document.querySelector('.sidebar nav');for(const [name,label,icon]of [['projects','Projects','projects'],['email','Email','mail']]){const b=document.createElement('button');b.className='nav-item';b.dataset.view=name;b.setAttribute('aria-label',label);b.innerHTML='<span data-icon="'+icon+'">'+ICONS[icon]+'</span><span class="nav-label">'+label+'</span>';b.onclick=()=>view(name);nav.append(b);}
 const scope=document.createElement('button');scope.id='project-scope';scope.className='project-scope';scope.type='button';scope.textContent='Choose project context';scope.onclick=()=>chooseProject();$('chat-form').before(scope);
 const calm=document.createElement('button');calm.className='calm-toggle';calm.textContent='Reduce visual effects';let reduced=false;try{reduced=localStorage.getItem('akilii-calm')==='true'}catch{}const set=()=>{document.documentElement.dataset.calm=String(reduced);calm.textContent=reduced?'Enable visual effects':'Reduce visual effects';calm.setAttribute('aria-pressed',String(reduced));};set();calm.onclick=()=>{reduced=!reduced;set();try{localStorage.setItem('akilii-calm',String(reduced))}catch{}};document.querySelector('.panel-footer').before(calm);
}
function chooseProject(){if(!window.akiliiAuth)return toast('Projects are available in the Google-enabled beta.');dialog('What are we working on?','<p>Only the project you select is included with your next message when “Use my context” is enabled.</p><button id="no-project" class="model-option">No project · a fresh conversation</button>'+X.projects.filter(p=>p.status==='active').map(p=>`<button class="model-option" data-select-project="${esc(p.id)}"><strong>${esc(p.title)}</strong><small>${esc(p.objective)}</small></button>`).join(''));$('no-project').onclick=()=>{X.projectId=null;applyWorkspace();$('dialog').close();};document.querySelectorAll('[data-select-project]').forEach(b=>b.onclick=()=>{X.projectId=b.dataset.selectProject;applyWorkspace();$('dialog').close();});}
function homeView(){
 const d=S.data;if(!d?.profile)return;const projects=X.projects.filter(p=>p.status==='active'),next=projects.flatMap(p=>p.tasks.filter(t=>!t.done).map(t=>({p,t}))).slice(0,X.settings.presentation==='one-step'?1:4);
 $('content-view').innerHTML=`<div class="home-hero"><span class="eyebrow">YOUR SPACE, TAKING SHAPE</span><h1>A little more possible,<br>${esc(d.profile.name)}.</h1><p>${esc(X.settings.objective||d.profile.focus||'Start with what matters. We’ll find a way that works for you.')}</p><div class="profile-chips"><span>${esc(X.settings.role||'Your role, your choice')}</span><span>${esc({'balanced':'A balanced view','one-step':'One step at a time','overview':'The bigger picture'}[X.settings.presentation])}</span></div><button id="shape-workspace">Shape my workspace ↗</button></div><div class="workspace-section-heading"><h2>${X.settings.presentation==='one-step'?'One thing to move forward.':'A path through your day.'}</h2><button id="home-new-project">New project +</button></div><div class="dashboard-grid">${next.map(({p,t})=>`<button class="next-step-card" data-open-project="${esc(p.id)}"><span class="eyebrow">${esc(p.title)}</span><h3>${esc(t.title)}</h3><span>Pick up here ↗</span></button>`).join('')||'<div class="next-step-card"><span class="eyebrow">A BEGINNING, NOT A BACKLOG</span><h3>Give one intention a place to grow.</h3><p>Create a small project or turn a useful response into one.</p></div>'}<button class="next-step-card conversation-card" id="home-start"><span class="eyebrow">THINK IT THROUGH</span><h3>Bring the messy version.</h3><p>No perfect prompt needed.</p><span>Start a conversation ↗</span></button></div><div class="workspace-stats"><span><strong>${projects.length}</strong> active projects</span><span><strong>${d.work.length}</strong> saved plans</span><span><strong>${d.memories.length}</strong> chosen preferences</span></div>`;
 $('shape-workspace').onclick=workspaceEditor;$('home-new-project').onclick=()=>projectEditor();$('home-start').onclick=resetChat;document.querySelectorAll('[data-open-project]').forEach(b=>b.onclick=()=>openProject(b.dataset.openProject));
}
function workspaceEditor(){if(!window.akiliiAuth)return toast('Workspace preferences are available in the Google-enabled beta.');const s=X.settings;dialog('Make it work like you do',`<form id="workspace-form"><p>These are your choices, not a psychological assessment. Change them as your situation changes.</p><label>My role or current chapter<input id="workspace-role" maxlength="100" value="${esc(s.role)}" placeholder="Founder, student, job seeker, parent…"></label><label>What I want to move towards<textarea id="workspace-objective" maxlength="2000">${esc(s.objective)}</textarea></label><label>What helps me work well<textarea id="workspace-needs" maxlength="2000" placeholder="Small starts, clear tradeoffs, protected focus time…">${esc(s.needs)}</textarea></label><label>How much would you like to see?<select id="workspace-presentation"><option value="balanced">A balanced view</option><option value="one-step">One step at a time</option><option value="overview">The bigger picture</option></select></label><p><small>Included in AI context only when “Use my context” is on. No archetype or diagnosis is inferred.</small></p><button class="primary">Save my choices</button><p class="error" role="alert"></p></form>`);$('workspace-presentation').value=s.presentation;bindForm('workspace-form',async()=>{await api('workspace','POST',{role:$('workspace-role').value,objective:$('workspace-objective').value,needs:$('workspace-needs').value,presentation:$('workspace-presentation').value});await loadWorkspace();$('dialog').close();toast('Your workspace reflects your choices.');});}
function projectsView(){if(!window.akiliiAuth){$('content-view').innerHTML='<h1>Projects</h1><p>Open the Google-enabled beta to use projects.</p>';return;}const projects=X.projects;$('content-view').innerHTML='<span class="eyebrow">INTENTIONS WITH A PLACE TO GROW</span><h1>Your projects.</h1><p>Keep the objective clear. Make the next step small enough to begin.</p><button id="create-project" class="primary">New project +</button><div class="dashboard-grid">'+projects.map(p=>{const done=p.tasks.filter(t=>t.done).length;return `<button class="project-card" data-project="${esc(p.id)}"><span class="eyebrow">${esc(p.status)}</span><h3>${esc(p.title)}</h3><p>${esc(p.objective)}</p><progress value="${done}" max="${p.tasks.length||1}" aria-label="Tasks completed"></progress><small>${done} of ${p.tasks.length} tasks complete</small></button>`;}).join('')+'</div>';$('create-project').onclick=()=>projectEditor();document.querySelectorAll('[data-project]').forEach(b=>b.onclick=()=>openProject(b.dataset.project));}
function projectEditor(object){if(!window.akiliiAuth)return toast('Projects are available in the Google-enabled beta.');dialog('Turn this into a project',`<form id="project-form"><label>Project name<input id="project-title" maxlength="120" required value="${esc(object?.title||'')}"></label><label>The outcome I want<textarea id="project-objective" maxlength="2000">${esc(object?.summary||'')}</textarea></label><label>Small steps · one per line<textarea id="project-tasks" maxlength="6000" placeholder="Start with one doable step">${esc(object?.items?.map(i=>i.label+(i.detail?' — '+i.detail:'')).join('\n')||'')}</textarea></label><p><small>Review the AI suggestions before saving. This creates a private project in your account.</small></p><button class="primary">Create my project</button><p class="error" role="alert"></p></form>`);bindForm('project-form',async()=>{const {project}=await api('projects','POST',{title:$('project-title').value,objective:$('project-objective').value,tasks:$('project-tasks').value.split('\n').filter(t=>t.trim()).map(title=>({title}))});await loadWorkspace();$('dialog').close();openProject(project.id);});}
function openProject(id){const p=X.projects.find(p=>p.id===id);if(!p)return;view('projects');const done=p.tasks.filter(t=>t.done).length;$('content-view').innerHTML=`<span class="eyebrow">${esc(p.status)} PROJECT</span><h1>${esc(p.title)}</h1><p>${esc(p.objective)}</p><div class="project-toolbar"><button id="think-project" class="primary">Think with akilii ↗</button><button id="project-status">${p.status==='active'?'Pause project':'Resume project'}</button><button id="complete-project">Mark complete</button><button id="export-project">Open in Excel · CSV</button><button id="remove-project">Delete project</button></div><div class="project-progress"><progress value="${done}" max="${p.tasks.length||1}"></progress><span>${done} of ${p.tasks.length} steps complete</span></div><div class="project-task-list">${p.tasks.map(t=>`<label class="project-task ${t.done?'done':''}"><input type="checkbox" data-task="${esc(t.id)}" ${t.done?'checked':''}><span>${esc(t.title)}</span></label>`).join('')}</div><form id="add-task-form" class="add-task"><label class="sr-only" for="new-task">Add a small step</label><input id="new-task" maxlength="300" required placeholder="Add a small step…"><button>Add step +</button><p class="error" role="alert"></p></form>`;
 const update=async changes=>{try{await api('projects/'+p.id,'POST',{version:p.version,...changes});}finally{await loadWorkspace();openProject(p.id);}};
 document.querySelectorAll('[data-task]').forEach(b=>b.onchange=safely(async()=>{b.disabled=true;await update({task_id:b.dataset.task,done:b.checked});}));$('export-project').onclick=()=>exportProjectCsv(p);$('think-project').onclick=()=>{X.projectId=p.id;applyWorkspace();view('chat');$('message-input').value='Help me move “'+p.title+'” forward. What is one useful next step?';$('message-input').focus();};$('project-status').onclick=safely(()=>update({status:p.status==='active'?'paused':'active'}));$('complete-project').onclick=safely(()=>update({status:'complete'}));$('remove-project').onclick=()=>confirmDelete('Delete this project?',async()=>{await api('projects/'+p.id,'DELETE');await loadWorkspace();view('projects');});bindForm('add-task-form',()=>update({add_task:$('new-task').value}));
}
function emailView(){$('content-view').innerHTML='<span class="eyebrow">LESS FRICTION, MORE CLARITY</span><h1>Find the right words.</h1><p>Prepare a thoughtful email, review it, and open it in your email app. Nothing is sent automatically.</p><div class="dashboard-grid"><button class="next-step-card" id="new-email"><span class="eyebrow">START FRESH</span><h3>A draft that sounds like you.</h3><span>Write an email ↗</span></button><button class="next-step-card" id="ai-email"><span class="eyebrow">THINK TOGETHER</span><h3>Something difficult to say?</h3><span>Draft with akilii ↗</span></button></div><p><small>Inbox synchronisation is not connected. Opening your email app shares only the draft you review.</small></p><div id="gmail-connection" class="context-card">Checking Gmail connection…</div>';loadGmailStatus();$('new-email').onclick=()=>emailEditor();$('ai-email').onclick=()=>{view('chat');$('message-input').value='Help me draft an email. Ask who it is for and what I want it to achieve.';$('message-input').focus();};}
function emailEditor(subject='',draft=''){dialog('Your words, your final say',`<form id="email-form"><label>To<input id="email-to" type="email" placeholder="recipient@example.com"></label><label>Subject<input id="email-subject" maxlength="180" value="${esc(subject)}"></label><label>Draft<textarea id="email-body" maxlength="10000" class="plan-body">${esc(draft)}</textarea></label><p><small>Review the recipient and wording. This opens your email app; you decide whether to send.</small></p><div class="dialog-actions"><button id="email-open" type="button" class="primary">Open in email app ↗</button><button id="gmail-draft" type="button">Create Gmail draft</button><button id="email-copy" type="button">Copy draft</button><button id="email-save" type="button">Save to Work</button></div><p class="error" role="alert"></p></form>`);$('email-form').onsubmit=e=>e.preventDefault();let requestKey=crypto.randomUUID();$('gmail-draft').onclick=safely(async()=>{const b=$('gmail-draft');b.disabled=true;const fields=['email-to','email-subject','email-body'].map($);fields.forEach(f=>f.readOnly=true);try{const status=await api('email/status');if(!status.connected){toast('Connect Gmail from Email first. Your draft is still here.');return;}if(!$('email-to').value||!$('email-to').checkValidity())throw new Error('Enter a valid recipient before creating a Gmail draft.');const r=await api('email/draft','POST',{to:$('email-to').value,subject:$('email-subject').value,body:$('email-body').value,request_key:requestKey});if(r.created){b.textContent='Draft created in Gmail';toast('Saved in Gmail Drafts. Nothing was sent.');b.dataset.created='true';}}finally{b.disabled=b.dataset.created==='true';fields.forEach(f=>f.readOnly=b.dataset.created==='true');}});$('email-open').onclick=()=>{const to=$('email-to');if(!to.checkValidity()){to.reportValidity();return;}const body=$('email-body').value;if(body.length>1800){toast('This draft is long. Copy it into your email app to avoid truncation.');return;}location.href='mailto:'+encodeURIComponent(to.value)+'?subject='+encodeURIComponent($('email-subject').value)+'&body='+encodeURIComponent(body);};$('email-copy').onclick=safely(async()=>{await navigator.clipboard.writeText('Subject: '+$('email-subject').value+'\n\n'+$('email-body').value);toast('Draft copied.');});$('email-save').onclick=()=>workEditor(null,'Subject: '+$('email-subject').value+'\n\n'+$('email-body').value);}
initExperience();

async function loadGmailStatus(){const target=$('gmail-connection');if(!target)return;if(!window.akiliiAuth){target.textContent='Gmail is available in the Google-enabled beta.';return;}try{const status=await api('email/status');target.innerHTML=status.connected?'<h3>Gmail is connected.</h3><p>Create reviewed drafts for up to one hour. No inbox messages are read.</p><button id="disconnect-gmail">Disconnect Gmail</button>':'<h3>Your email, with a little less friction.</h3><p>Connect Gmail to create a draft directly after you review it.</p><button id="connect-gmail">Connect Gmail</button>';if(status.connected)$('disconnect-gmail').onclick=safely(async()=>{await api('email/disconnect','POST',{});await loadGmailStatus();toast('Gmail access removed from akilii. Existing drafts remain in Gmail.');});else $('connect-gmail').onclick=()=>{if(!status.available)return toast('Gmail setup is still being completed.');dialog('Connect Gmail for drafts','<p>Google will ask for permission to manage drafts and send email. This build uses that permission only to create drafts you explicitly review; it has no send function and does not read your inbox.</p><p>The encrypted connection lasts up to one hour, then you reconnect. Disconnect removes the stored access token from akilii. You can also revoke the Google permission in your Google Account settings.</p><button id="authorise-gmail" class="primary">Continue to Google</button>');$('authorise-gmail').onclick=safely(window.akiliiAuth.connectGmail);};}catch(e){target.textContent=e.message;}}

function appendWorkspaceContext(){if(!X.loaded)return;const selected=X.projects.find(p=>p.id===X.projectId);const card=document.createElement('div');card.className='context-card workspace-context';card.innerHTML='<span class="eyebrow">CHOSEN BY YOU</span><h4>'+esc(X.settings.role||'Your working context')+'</h4><p>'+esc(X.settings.objective||X.settings.needs||'Shape your workspace around what helps you.')+'</p>'+(selected?'<small>Selected project</small><p>'+esc(selected.title)+' · '+selected.tasks.filter(t=>!t.done).length+' steps remaining</p>':'')+'<button id="panel-shape">Adjust my workspace</button>';$('context-content').prepend(card);$('panel-shape').onclick=workspaceEditor;}
