// Temporary presentation preferences; never a diagnosis or durable profile inference.
let supportState='standard';
function supportInstruction(){return supportState;}
function applySupportState(value){if(!['standard','focus','gentle','engage'].includes(value))return;supportState=value;document.documentElement.dataset.support=value;document.getElementById('support-checkin').textContent={standard:'What would help right now?',focus:'One thing at a time · change',gentle:'Gentler pace · change',engage:'A different approach · change'}[value];document.querySelectorAll('.response-object').forEach(card=>{if(!card.dataset.viewChosen)card.setPresentation?.(['focus','gentle'].includes(value)||X.settings.presentation==='one-step'?'one':'overview');});}
function supportCheckin(){dialog('What would help right now?',`<p>You choose what fits. A pause or change in typing does not tell akilii how you feel.</p><div class="support-choices"><button data-support="focus">I’m distracted<small>One step at a time, less visual movement.</small></button><button data-support="gentle">I’m tired or this feels too much<small>A gentler view and shorter responses.</small></button><button data-support="engage">I’m finding it hard to engage<small>Try a different explanation or a few choices.</small></button><button data-support="standard">My usual view<small>Remove this temporary adjustment.</small></button></div><p><small>This applies in this open session only. The chosen response style is sent with your next message; these check-in labels are not added to your profile. You can change or undo it at any time.</small></p>`);document.querySelectorAll('.support-choices [data-support]').forEach(b=>b.onclick=()=>{applySupportState(b.dataset.support);$('dialog').close();toast('Adjusted for now. You can change this whenever you want.');});}
function enhanceGenerativeCard(card,object){
 const toolbar=document.createElement('div');toolbar.className='genui-toolbar';toolbar.setAttribute('role','group');toolbar.setAttribute('aria-label','Response presentation');
 const text=document.createElement('div');text.className='genui-plain';text.hidden=true;const refreshPlain=()=>{text.textContent=[object.title,object.summary,...object.items.map(i=>i.label+(i.detail?' — '+i.detail:'')),object.draft].filter(Boolean).join('\n\n');};refreshPlain();
 const setView=value=>{card.dataset.genView=value;text.hidden=value!=='plain';for(const b of toolbar.querySelectorAll('button'))b.setAttribute('aria-pressed',String(b.dataset.genView===value));};
 for(const [value,label]of [['one','One step'],['overview','Overview'],['plain','Plain text']]){const b=document.createElement('button');b.type='button';b.textContent=label;b.dataset.genView=value;b.onclick=()=>{card.dataset.viewChosen='true';setView(value);};toolbar.append(b);}
 card.setPresentation=setView;card.prepend(toolbar);card.append(text);setView(['focus','gentle'].includes(supportState)||X.settings.presentation==='one-step'?'one':'overview');
 if(object.type==='decision'){for(const [index,row]of [...card.querySelectorAll('.object-item')].entries()){const b=document.createElement('button');b.type='button';b.textContent='Explore this option';b.onclick=()=>{if(S.busy)return toast('Stop or finish the current response first.');const input=$('message-input'),prompt='Let’s explore “'+object.items[index].label+'” from “'+object.title+'”. Help me assess whether it fits.';if(input.value.trim())return toast('Keep or clear your current draft before choosing an option.');input.value=prompt;input.dispatchEvent(new Event('input',{bubbles:true}));input.focus();};row.append(b);}}
 if(object.type==='email'&&object.draft){const old=card.querySelector('.email-preview');if(old){const field=document.createElement('textarea');field.className='genui-draft';field.value=object.draft;field.maxLength=10000;field.setAttribute('aria-label','Edit '+object.title);field.oninput=()=>{object.draft=field.value;refreshPlain();};old.replaceWith(field);const note=document.createElement('small');note.textContent='Edits here are temporary. Save to Work to keep them.';field.after(note);const save=document.createElement('button');save.type='button';save.textContent='Save edited draft to Work';save.onclick=()=>workEditor(null,object.title+'\n\n'+field.value);card.querySelector('.object-actions').prepend(save);}}
 const rows=[...card.querySelectorAll('.object-item')];if(rows.length>1){let index=0;const next=document.createElement('button');next.type='button';next.className='genui-next';const update=()=>{rows.forEach((r,i)=>r.dataset.current=String(i===index));next.textContent=index===rows.length-1?'Back to first item':'Next item · '+(index+2)+' of '+rows.length;};next.onclick=()=>{index=(index+1)%rows.length;update();};update();toolbar.after(next);}
}
const checkin=document.createElement('button');checkin.type='button';checkin.id='support-checkin';checkin.className='support-checkin';checkin.textContent='What would help right now?';checkin.onclick=supportCheckin;document.getElementById('smart-prompts').before(checkin);
