function chooseSmartPrompts({hasReply=false,question=false,project=false,attachment=false,draft=false}={}){
 if(draft)return [{label:'Help me phrase this',prompt:'Help me put the thought above into clear words. Ask one short question if you need clarification.'},{label:'Find the main point',prompt:'Help me identify the main point in what I have written above.'},{label:'One step at a time',prompt:'Please work through this with me one short step at a time.'}];
 if(attachment)return [{label:'Explain this simply',prompt:'Explain the attached excerpt in plain language, starting with the most useful point.'},{label:'What matters here?',prompt:'What are the key points in this excerpt for the activity we are discussing? Ask me about my aim if it is unclear.'},{label:'Help me respond',prompt:'Help me work out how to respond to this excerpt. Ask one short question at a time.'}];
 if(question)return [{label:'Give me a few choices',prompt:'I’m not sure how to answer your last question. Could you give me two or three simple options, including a way to say something else?'},{label:'Ask it more simply',prompt:'Please rephrase your last question more simply and ask only one thing.'},{label:'I’m not sure yet',prompt:'I’m not sure yet. Help me explore this gently, without assuming an answer for me.'}];
 if(project)return [{label:'Smallest next step',prompt:'For the project I selected, help me choose one small next step.'},{label:'Help me prioritise',prompt:'Help me decide what matters first for the selected project. Keep the choices manageable.'},{label:'Make it manageable',prompt:'Help me make the next part of this project manageable. Ask what feels difficult rather than assuming.'}];
 if(hasReply)return [{label:'Explain more simply',prompt:'Please explain your last response more simply and briefly.'},{label:'Just one next step',prompt:'Please give me just one small next step from what we discussed.'},{label:'Something doesn’t fit',prompt:'Something in your response does not fit. Help me identify what needs changing, one question at a time.'}];
 return [{label:'Help me find a start',prompt:'I’m not sure where to start. Ask me one short question to help me find a starting point.'},{label:'Untangle a thought',prompt:'Help me untangle a thought. I may not explain it clearly at first; ask one thing at a time.'},{label:'Give me some choices',prompt:'Help me choose what to work on with a few simple options. Please do not assume my priorities.'}];
}
function renderSmartPrompts(){const host=document.getElementById('smart-prompts'),input=document.getElementById('message-input');if(!host||!input)return;host.hidden=S.busy;const toggle=document.getElementById('smart-prompts-toggle'),list=document.getElementById('smart-prompts-list');let hidden=false;try{hidden=sessionStorage.getItem('akilii-hide-prompts')==='1';}catch{}toggle.textContent=hidden?'Show conversation helpers':'Hide helpers';toggle.setAttribute('aria-expanded',String(!hidden));list.hidden=hidden;list.replaceChildren();if(hidden)return;
 const last=[...S.messages].reverse().find(m=>m.role==='assistant');let text=last?.content||'';try{text=JSON.parse(text).message||text;}catch{}
 for(const option of chooseSmartPrompts({hasReply:!!last,question:/\?\s*$/.test(text.trim()),project:!!X.projectId,attachment:!!S.attachment,draft:!!input.value.trim()})){const b=document.createElement('button');b.type='button';b.className='smart-chip';b.textContent=option.label;b.title='Add to your draft: '+option.prompt;b.onclick=()=>{if(S.busy)return;const next=(input.value.trim()?input.value.trim()+'\n\n':'')+option.prompt;if(next.length>input.maxLength)return toast('Your draft is full. Shorten it before adding a helper.');input.value=next;input.dispatchEvent(new Event('input',{bubbles:true}));input.focus();toast('Added to your draft. Edit it or send when you’re ready.');};list.append(b);}
}
document.getElementById('smart-prompts-toggle').onclick=()=>{try{sessionStorage.setItem('akilii-hide-prompts',sessionStorage.getItem('akilii-hide-prompts')==='1'?'0':'1');}catch{}renderSmartPrompts();};
document.getElementById('message-input').addEventListener('input',renderSmartPrompts);
renderSmartPrompts();
