let previewAudio=null,previewUrl=null,previewRequest=0;
const voiceSampleCache=new Map();
function stopVoiceSample(){previewRequest++;if(previewAudio){previewAudio.pause();previewAudio=null;}if(previewUrl){URL.revokeObjectURL(previewUrl);previewUrl=null;}document.querySelectorAll('[data-voice-preview]').forEach(b=>{b.disabled=false;b.textContent='▶ Preview';});}
function suggestedVoiceSettings(settings={},lastVoice){const valid=['marin','cedar','coral','sage','ash','ballad','echo','shimmer','verse','alloy'];return {voices:valid.includes(lastVoice)?[lastVoice]:['marin','cedar'],speed:settings.presentation==='one-step'?0.85:1,reason:valid.includes(lastVoice)?'Your previous choice is highlighted. Listen again or explore another voice.':settings.presentation==='one-step'?'You chose one step at a time, so a slower pace is suggested. Try these starting voices and choose what feels comfortable.':'Marin and Cedar are suggested starting voices for audio quality. Your own listening preference matters most.'};}
function voiceCards(names,suggested){return names.map(name=>`<div class="voice-card"><button type="button" data-voice-select="${name}" aria-pressed="false"><span class="voice-avatar" aria-hidden="true">${name[0].toUpperCase()}</span><span><strong>${name[0].toUpperCase()+name.slice(1)}</strong>${suggested.includes(name)?'<small>Suggested starting voice</small>':'<small>Listen and compare</small>'}</span><span class="voice-check" aria-hidden="true">✓</span></button><button type="button" data-voice-preview="${name}" aria-label="Preview ${name[0].toUpperCase()+name.slice(1)}">▶ Preview</button></div>`).join('');}
function initVoicePicker(){let last;try{last=localStorage.getItem('akilii-voice');}catch{}const recommendation=suggestedVoiceSettings(X.settings,last);$('voice-choice').value=recommendation.voices[0];$('voice-speed').value=String(recommendation.speed);$('voice-recommendation').textContent=recommendation.reason;
 $('voice-card-list').innerHTML=voiceCards(recommendation.voices,recommendation.voices);$('voice-more-list').innerHTML=voiceCards(['marin','cedar','coral','sage','ash','ballad','echo','shimmer','verse','alloy'].filter(v=>!recommendation.voices.includes(v)),[]);
 const update=()=>document.querySelectorAll('[data-voice-select]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.voiceSelect===$('voice-choice').value)));
 document.querySelectorAll('[data-voice-select]').forEach(b=>b.onclick=()=>{stopVoiceSample();$('voice-choice').value=b.dataset.voiceSelect;update();});update();
 document.querySelectorAll('[data-voice-preview]').forEach(button=>button.onclick=async()=>{stopVoiceSample();const request=previewRequest;const voice=button.dataset.voicePreview,speed=Number($('voice-speed').value),key=voice+':'+speed;button.disabled=true;button.textContent='Loading…';$('voice-sample-status').textContent='Preparing '+voice+'…';try{let sample=voiceSampleCache.get(key);if(!sample){sample=await api('voice/preview','POST',{voice,speed});voiceSampleCache.set(key,sample);}if(request!==previewRequest)return;if(sample.mime!=='audio/mpeg'||!sample.audio)throw new Error('This sample is unavailable.');const bytes=Uint8Array.from(atob(sample.audio),c=>c.charCodeAt(0));previewUrl=URL.createObjectURL(new Blob([bytes],{type:sample.mime}));previewAudio=new Audio(previewUrl);previewAudio.onended=()=>{stopVoiceSample();if($('voice-sample-status'))$('voice-sample-status').textContent='Sample finished. Choose the voice you prefer.';};await previewAudio.play();button.disabled=false;button.textContent='↻ Replay';$('voice-sample-status').textContent='Playing '+voice+'. This is an AI-generated sample; live delivery can vary.';}catch(e){if(request===previewRequest){stopVoiceSample();if($('voice-sample-status'))$('voice-sample-status').textContent=e.message||'Playback was blocked. Try Preview again.';}}});
 $('voice-speed').onchange=stopVoiceSample;$('voice-sample-stop').onclick=stopVoiceSample;
}
$('dialog').addEventListener('close',stopVoiceSample);window.addEventListener('pagehide',stopVoiceSample);
