const {randomBytes,createHash}=require('node:crypto');
const project='https://xmesqilkgeaoqrxbooqe.supabase.co';const apikey='sb_publishable_wdcht-0QIvLwbBIj7StxIQ_UTV2qCfc';
function cloudSession(openExternal,fetchImpl=globalThis.fetch,config=require('./auth-options.json')){let pending=null,session=null,epoch=0;let lastEmail=0;const acceptSession=(data,version=epoch)=>{if(version!==epoch)throw Error('Sign-in was cancelled. Please start again.');if(!data?.access_token||!data.refresh_token||!Number.isFinite(data.expires_in))throw Error('Sign-in returned an invalid session.');session=data;session.expires_at=Date.now()+session.expires_in*1000;};const authFetch=(route,body)=>fetchImpl(project+'/auth/v1/'+route,{method:body?'POST':'GET',headers:{apikey,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(15000)});
 return {async options(){const r=await authFetch('settings');if(!r.ok)throw Error('Sign-in unavailable.');const d=await r.json();return {google:d.external?.google===true,azure:d.external?.azure===true,email:config.emailOtpReady&&d.external?.email===true};},async sendCode(email){if(!config.emailOtpReady)throw Error('Email sign-in is awaiting email-service setup.');if(typeof email!=='string'||email.length>254||!/^\S+@\S+\.\S+$/.test(email))throw Error('Enter a valid email address.');if(Date.now()-lastEmail<60000)throw Error('Wait a minute before requesting another code.');lastEmail=Date.now();epoch++;pending=null;const r=await authFetch('otp',{email,create_user:true});if(!r.ok)throw Error('The code could not be sent. Check the address or wait before retrying.');},async verifyCode(email,token){if(typeof email!=='string'||email.length>254||typeof token!=='string'||!/^\d{6,10}$/.test(token))throw Error('Enter the sign-in code from your email.');const version=epoch;const r=await authFetch('verify',{email,token,type:'email'});if(!r.ok)throw Error('That code is invalid or expired. Request a new code.');acceptSession(await r.json(),version);pending=null;},async signIn(provider='google'){if(!['google','azure'].includes(provider))throw Error('Choose a supported sign-in option.');epoch++;const verifier=randomBytes(48).toString('base64url'),nonce=randomBytes(24).toString('hex');pending={verifier,nonce,version:epoch,until:Date.now()+600000};const target=new URL(project+'/auth/v1/authorize');target.search=new URLSearchParams({provider,...(provider==='azure'?{scopes:'email'}:{}),redirect_to:'https://fullspektrum-ai.github.io/akilii/?desktop_callback='+nonce,code_challenge:createHash('sha256').update(verifier).digest('base64url'),code_challenge_method:'s256',prompt:'select_account'}).toString();await openExternal(target.href);},
 async accept(value){let u;try{u=new URL(value);}catch{return false;}if(u.protocol!=='akilii:'||u.hostname!=='auth'||!pending||pending.until<Date.now()||u.searchParams.get('state')!==pending.nonce)return false;const p=pending;pending=null;const code=u.searchParams.get('code');if(!code||code.length>2048)return false;let r;try{r=await fetchImpl(project+'/auth/v1/token?grant_type=pkce',{method:'POST',headers:{apikey,'Content-Type':'application/json'},body:JSON.stringify({auth_code:code,code_verifier:p.verifier})});}catch{throw new Error('Sign-in could not connect. Please check your connection and start sign-in again.');}if(!r.ok)throw new Error('Sign-in expired or was rejected. Please start sign-in again.');acceptSession(await r.json(),p.version);return true;},
 async request(req){if(!session)return new Response(JSON.stringify({error:'Sign in to use your cloud workspace.'}),{status:401,headers:{'Content-Type':'application/json'}});if(session.expires_at<Date.now()+60000){const version=epoch;const r=await fetchImpl(project+'/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:{apikey,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:session.refresh_token})});if(!r.ok){session=null;return new Response('{"error":"Please sign in again."}',{status:401});}acceptSession(await r.json(),version);}
 const u=new URL(req.url);return fetchImpl(project+'/functions/v1/akilii-api'+u.pathname+u.search,{method:req.method,signal:req.signal,headers:{apikey,Authorization:'Bearer '+session.access_token,Origin:'https://fullspektrum-ai.github.io','Content-Type':'application/json'},body:['GET','HEAD'].includes(req.method)?undefined:await req.text()});},async signOut(){const previous=session;epoch++;session=null;pending=null;if(previous)try{await fetchImpl(project+'/auth/v1/logout?scope=local',{method:'POST',headers:{apikey,Authorization:'Bearer '+previous.access_token},signal:AbortSignal.timeout(10000)});}catch{}}};
}
module.exports={cloudSession};
