const {randomBytes,createHash}=require('node:crypto');
const project='https://xmesqilkgeaoqrxbooqe.supabase.co';const apikey='sb_publishable_wdcht-0QIvLwbBIj7StxIQ_UTV2qCfc';
function cloudSession(openExternal,fetchImpl=globalThis.fetch){let pending=null,session=null;
 return {async signIn(){const verifier=randomBytes(48).toString('base64url'),nonce=randomBytes(24).toString('hex');pending={verifier,nonce,until:Date.now()+600000};const target=new URL(project+'/auth/v1/authorize');target.search=new URLSearchParams({provider:'google',redirect_to:'https://fullspektrum-ai.github.io/akilii/?desktop_callback='+nonce,code_challenge:createHash('sha256').update(verifier).digest('base64url'),code_challenge_method:'s256',prompt:'select_account'}).toString();await openExternal(target.href);},
 async accept(value){let u;try{u=new URL(value);}catch{return false;}if(u.protocol!=='akilii:'||u.hostname!=='auth'||!pending||pending.until<Date.now()||u.searchParams.get('state')!==pending.nonce)return false;const p=pending;pending=null;const code=u.searchParams.get('code');if(!code||code.length>2048)return false;let r;try{r=await fetchImpl(project+'/auth/v1/token?grant_type=pkce',{method:'POST',headers:{apikey,'Content-Type':'application/json'},body:JSON.stringify({auth_code:code,code_verifier:p.verifier})});}catch{throw new Error('Google sign-in could not connect. Please check your connection and start sign-in again.');}if(!r.ok)throw new Error('Google sign-in expired or was rejected. Please start sign-in again.');session=await r.json();session.expires_at=Date.now()+session.expires_in*1000;return true;},
 async request(req){if(!session)return new Response(JSON.stringify({error:'Sign in with Google to use your cloud workspace.'}),{status:401,headers:{'Content-Type':'application/json'}});if(session.expires_at<Date.now()+60000){const r=await fetchImpl(project+'/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:{apikey,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:session.refresh_token})});if(!r.ok){session=null;return new Response('{"error":"Please sign in again."}',{status:401});}session=await r.json();session.expires_at=Date.now()+session.expires_in*1000;}
 const u=new URL(req.url);return fetchImpl(project+'/functions/v1/akilii-api'+u.pathname+u.search,{method:req.method,signal:req.signal,headers:{apikey,Authorization:'Bearer '+session.access_token,Origin:'https://fullspektrum-ai.github.io','Content-Type':'application/json'},body:['GET','HEAD'].includes(req.method)?undefined:await req.text()});},signOut(){session=null;pending=null;}};
}
module.exports={cloudSession};
